# Generated by Django 5.2.3 on 2025-07-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0002_college_course'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='sos_course',
        ),
    ]
