# Generated by Django 5.2.3 on 2025-07-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0003_alter_course_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('courseId', models.IntegerField()),
                ('courseName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_subject',
            },
        ),
    ]
