# Generated by Django 5.2.3 on 2025-07-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0004_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('collegeId', models.IntegerField()),
                ('collegeName', models.CharField(max_length=50)),
                ('subjectId', models.IntegerField()),
                ('subjectName', models.CharField(max_length=50)),
                ('courseId', models.IntegerField()),
                ('courseName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_faculty',
            },
        ),
    ]
