# Generated by Django 5.2.3 on 2025-07-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0005_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('maths', models.IntegerField()),
            ],
            options={
                'db_table': 'sos_marksheet',
            },
        ),
    ]
