# Generated by Django 5.2.3 on 2025-07-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0006_marksheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('collegeId', models.IntegerField()),
                ('collegeName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_student',
            },
        ),
    ]
