# Generated by Django 5.2.3 on 2025-07-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0007_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examTime', models.CharField(max_length=40)),
                ('examDate', models.DateField()),
                ('subjectId', models.IntegerField()),
                ('subjectName', models.CharField(max_length=50)),
                ('courseId', models.IntegerField()),
                ('courseName', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_timetable',
            },
        ),
    ]
